version: 2
jobs:
  build:
    working_directory: /work
    docker:
      - image: node:12.9.0
    steps:
      - checkout
      - restore_cache:
          name: Package cache restored
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Package cache saved
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Testing
          command: npm test
      - run:
          name: Deploy to zeit/now
          command: yarn build && yarn deploy
