version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root /tmp/work

image: &image circleci/node:14.2.0

node_modules_dir: &node_modules_dir node_modules/

###########################################
# Jobs Definitions
###########################################
jobs:
  init:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - restore_cache:
          name: Package cache restored
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Package cache saved
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./.next/cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *node_modules_dir

  script_lint:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Run ESLint
          command: yarn script_lint

  style_lint:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Run stylelint
          command: yarn style_lint

  check_format:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Is auto formatting done
          command: yarn check_format

  test:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Testing
          command: yarn test

  build:
    working_directory: *workspace_root
    docker:
      - image: *image
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Build
          command: yarn build

###########################################
# Workflow Definitions
###########################################
workflows:
  version: 2
  ci_workflow:
    jobs:
      - init
      - script_lint:
          requires:
            - init
      - style_lint:
          requires:
            - init
      - check_format:
          requires:
            - init
      - test:
          requires:
            - init
      - build:
          requires:
            - init
