version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root /tmp/work

node_modules_dir: &node_modules_dir node_modules/

defaults: &defaults
  working_directory: *workspace_root

###########################################
# Executor Definitions
###########################################
executors:
  build_executor:
    <<: *defaults
    docker:
      - image: circleci/node:12.9.0

jobs:
  init:
    executor: build_executor
    steps:
      - checkout
      - restore_cache:
          name: Package cache restored
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Package cache saved
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *node_modules_dir

  script_lint:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Run ESLint
          command: yarn script_lint

  style_lint:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Run stylelint
          command: yarn style_lint

  check_format:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Is auto formatting done
          command: yarn check_format

  test:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Testing
          command: yarn test

  staging_deploy:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Deploy to zeit/now staging
          command: yarn build && yarn staging_deploy

  prod_deploy:
    executor: build_executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Deploy to zeit/now production
          command: yarn build && yarn prod_deploy

###########################################
# Workflow Conditions
###########################################
cond_filters_trunk: &cond_filters_trunk
  branches:
    only: master

cond_filters_ignore_trunk: &cond_filters_ignore_trunk
  branches:
    ignore: master

###########################################
# Workflow Definitions
###########################################
workflows:
  version: 2
  ci_workflow:
    jobs:
      - init
      - script_lint:
          requires:
            - init
      - style_lint:
          requires:
            - init
      - check_format:
          requires:
            - init
      - test:
          requires:
            - init
      - staging_deploy:
          requires:
            - script_lint
            - style_lint
            - check_format
            - test
          filters:
            <<: *cond_filters_ignore_trunk
      - prod_deploy:
          requires:
            - script_lint
            - style_lint
            - check_format
            - test
          filters:
            <<: *cond_filters_trunk