CREATE TABLE likes (
  id SERIAL PRIMARY KEY,
  entry_id VARCHAR(255) NOT NULL UNIQUE,
  counts INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_entry_id ON likes (entry_id);
