name = "@kubosho/blog-api"
main = "src/index.ts"
compatibility_date = "2024-12-29"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# Database connection URL (set in production environment)
# DATABASE_URL = "postgresql://username:password@hostname:port/database"

# Rate limiting binding (configured in Cloudflare dashboard)
# RATE_LIMITER binding will be added via Cloudflare Workers dashboard

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
