name = "kubosho-blog-api"
main = "src/index.ts"
compatibility_date = "2024-12-29"

# Enable nodejs compatibility for Sentry
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# Environment variables
[vars]
ENVIRONMENT = "production"
RELEASE_VERSION = "1.0.0"

# Database configuration
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "d124e91279e647eea9e18a42f340ef25"
localConnectionString = "postgresql://postgres:postgres@localhost:5432/main"

# Rate limiting configuration
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
# Simple rate limiting rule: 60 requests per minute per IP
simple = { limit = 60, period = 60 }
