name = "kubosho-blog-api"
main = "src/index.ts"
compatibility_date = "2024-12-29"

# Enable nodejs compatibility for Sentry
compatibility_flags = [ "nodejs_compat" ]

# Environment variables
[vars]
ENVIRONMENT = "production"
RELEASE_VERSION = "1.0.0"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

# Database configuration
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "HYPERDRIVE_ID"

# Rate limiting configuration
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
# Simple rate limiting rule: 60 requests per minute per IP
simple = { limit = 60, period = 60 }
