name: Checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    defaults:
      run:
        working-directory: client

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install modules
        run: npm ci

      - name: Check TypeScript code
        run: |
          npx astro sync
          npm run check:ts

      - name: Check formatting
        run: npm run check:format
