name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    defaults:
      run:
        working-directory: client

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install modules
        run: npm ci

      - name: Run lints
        run: |
          npm run lint:script
          npm run lint:style
          npm run lint:markup
