name: Release

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: yarn
      - name: release script
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
