name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TZ: 'Asia/Tokyo'

jobs:
  test:
    defaults:
      run:
        working-directory: client

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install modules
        run: npm ci

      - name: Run testing
        run: npm test
