name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: npm ci
      - name: Run lint
        run: |
          npm run script_lint
          npm run style_lint
          npm run markup_lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: npm ci
      - name: Check TypeScript code
        run: npm run check_ts
      - name: Run testing
        run: npm test
